version: "3.9"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea-app
    secrets:
      - security_key
      - internal_token
      - gitea_db_name
      - gitea_db_user
      - gitea_db_password
      - gitea_mailer_from
      - gitea_mailer_host
      - gitea_mailer_user
      - gitea_mailer_password
      - postgres_user
      - postgres_password
      - postgres_db
      
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: /run/secrets/gitee_db_type
      GITEA__database__HOST: /run/secrets/gitea_db_host
      GITEA__database__NAME: /run/secrets//gitea_db_name
      GITEA__database__USER: /run/secrets/gitea_db_user
      GITEA__database__PASSWD: /run/secrets/gitea_db_passwd

      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: /run/secrets/gitea_mailer_from:?GITEA__mailer__FROM not set
      GITEA__mailer__MAILER_TYPE: smtp
      GITEA__mailer__HOST: /run/secrets/gitea_mailer_hostname:?GITEA__mailer__HOST not set
      GITEA__mailer__IS_TLS_ENABLED: true
      GITEA__mailer__USER: /run/secrets/gitea_mailer_user:?GITEA__mailer__IS_TLS_ENABLED
      GITEA__mailer__PASSWD: /run/secrets/gitea_mailer_apsswd:?GITEA__mailer__PASSWD not set

      GITEA__security__SECRET_KEY: /run/secrets/secret_key
      GITEA__security__INTERNAL_TOKEN: /run/secrets/internal_token
    restart: always
    networks:
      - gitea
    volumes:
      - ${APP_DATA_ROOT}/data:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "10122:22"
    depends_on:
      - db

  postgres:
    image: postgres:14
    container_name: gitea-postgres
    restart: always
    environment:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_DB: /run/secrets/postgres_db
    networks:
      - gitea
    ports:
      - "5433:5432"
    volumes:
      - ${DB_DATA_ROOT}:/var/lib/postgresql/data

secrets:
  security_key:
    file: ./secrets/security_key
  internal_token:
    file: ./secrets/internal_token
  gitea_db_type:
    file: ./secrets/gitea_db_type
  gitea_db_Hostname:
    file: ./secrets/gitea_db_hostname
  gitea_db_name:
    file: ./secrets/gitea_db_name
  gitea_db_user:
    file: ./secrets/gitea_db_user
  gitea_db_password:
    file: ./secrets/gitea_db_password
  gitea_mailer_from:
    file: ./secrets/gitea_mailer_from
  gitea_mailer_host:
    file: ./secrets/gitea_mailer_host
  gitea_mailer_user:
    file: ./secrets/gitea_mailer_user
  gitea_mailer_password:
    file: ./secrets/gitea_mailer_password
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  postgres_db:
    file: ./secrets/postgres_db