version: "3.8"

networks:
  gitea:
    external: false

services:
  server:
    image: jessenich91/gitea:1.15.6
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - "8080:3000"
    - "2222:22"