version: "3.9"

networks:
  gitea-net-public:
    external: false
  gitea-net-private:
    external: false

services:
  git:
    image: gitea/gitea:latest
    container_name: gitea-git
    secrets:
      - security_key
      - internal_token
      - gitea_db_name
      - gitea_db_user
      - gitea_db_passwd
      - gitea_mailer_from
      - gitea_mailer_host
      - gitea_mailer_user
      - gitea_mailer_passwd
      - postgres_user
      - postgres_passwd
      - postgres_db
    environment:
      - USER_UID=${APP_USER_UID}
      - USER_GID=${APP_USER_GID}
      - GITEA__database__DB_TYPE=/run/secrets/gitea_db_type
      - GITEA__database__HOST=/run/secrets/gitea_db_host
      - GITEA__database__NAME=/run/secrets/gitea_db_name
      - GITEA__database__USER=/run/secrets/gitea_db_user
      - GITEA__database__PASSWD=/run/secrets/gitea_db_passwd

      - GITEA__mailer__ENABLED=false
      - GITEA__mailer__FROM=/run/secrets/gitea_mailer_from:?GITEA__mailer__FROM not set
      - GITEA__mailer__MAILER_TYPE=smtp
      - GITEA__mailer__HOST=/run/secrets/gitea_mailer_host:?GITEA__mailer__HOST not set
      - GITEA__mailer__IS_TLS_ENABLED=true
      - GITEA__mailer__USER=/run/secrets/gitea_mailer_user:?GITEA__mailer__USER not set
      - GITEA__mailer__PASSWD=/run/secrets/gitea_mailer_passwd:?GITEA__mailer__PASSWD not set

      - GITEA__security__SECRET_KEY=/run/secret/secret_key
      - GITEA__security__INTERNAL_TOKEN=/run/secrets/internal_token
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:git.sycuryx.me"
      - "traefik.docker.network=hakasenet"
      - "traefik.port=3000"
    restart: always
    networks:
      - gitea-net-public
    volumes:
      - ${APP_DATA_ROOT}/data:/data
      - ${APP_DATA_ROOT}/data/git/.ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "10122:22"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: gitea-db
    restart: always
    secrets:
      - postgres_user
      - postgres_passwd
      - postgres_db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_passwd
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    labels:
      - "traefik.enable=false"
    networks:
      - gitea-net-private
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DATA_ROOT}:/var/lib/postgresql/data

  reverse-proxy:
    image: traefik:latest
    command: --docker
    ports:
      - 10080:80
      - 10443:443
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:traefik.sycuryx.me"
      - "traefik.port=8080"
    networks:
      - gitea-net-private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: gitea-reverse-proxy
    restart: always

secrets:
  security_key:
    file: ./.secrets/security_key
    environment:
      GITEA__security__SECRET_KEY=/run/secret/security_key
  internal_token:
    file: ./.secrets/internal_token
  gitea_db_type:
    file: ./.secrets/gitea_db_type
  gitea_db_Hostname:
    file: ./.secrets/gitea_db_hostname
  gitea_db_name:
    file: ./.secrets/gitea_db_name
  gitea_db_user:
    file: ./.secrets/gitea_db_user
  gitea_db_passwd:
    file: ./.secrets/gitea_db_passwd
  gitea_mailer_from:
    file: ./.secrets/gitea_mailer_from
  gitea_mailer_host:
    file: ./.secrets/gitea_mailer_host
  gitea_mailer_user:
    file: ./.secrets/gitea_mailer_user
  gitea_mailer_passwd:
    file: ./.secrets/gitea_mailer_passwd
  postgres_user:
    file: ./.secrets/postgres_user
  postgres_passwd:
    file: ./.secrets/postgres_passwd
  postgres_db:
    file: ./.secrets/postgres_db